

# services:
#  attu:
#    container_name: attu
#    restart: always
#    image: zilliz/attu:v2.3.10
#    ports:
#      - 8887:3000
#    environment:
#      - MILVUS_URL=milvus:19530
#
#  dozzle:
#    container_name: dozzle
#    image: amir20/dozzle:latest
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - 8888:8080
#
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    restart: always
#    ports:
#      - "8889:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: dev@jember.ai
#      PGADMIN_DEFAULT_PASSWORD: password
#
#  postgres:
#    container_name: postgres
#    image: postgres:${POSTGRES_IMAGE_TAG:-14-alpine}
#    restart: always
#    ports:
#      - 5432:5432
#    volumes:
#      - ./cfg/postgres/initdb:/docker-entrypoint-initdb.d
#     # - ./db/postgres/data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=postgres
#
#  etcd:
#    container_name: etcd
#    image: quay.io/coreos/etcd:v3.5.0
#    environment:
#      - ETCD_AUTO_COMPACTION_MODE=revision
#      - ETCD_AUTO_COMPACTION_RETENTION=1000
#      - ETCD_QUOTA_BACKEND_BYTES=4294967296
#    volumes:
#      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
#    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
#
#  minio:
#    container_name: minio
#    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
#    environment:
#      MINIO_ACCESS_KEY: minioadmin
#      MINIO_SECRET_KEY: minioadmin
#    volumes:
#      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
#    command: minio server /minio_data
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
#      interval: 30s
#      timeout: 20s
#      retries: 3
#
#  milvus:
#    container_name: milvus
#    image: milvusdb/milvus:v2.0.2
#    command: ["milvus", "run", "standalone"]
#    environment:
#      ETCD_ENDPOINTS: etcd:2379
#      MINIO_ADDRESS: minio:9000
#    volumes:
#      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
#    ports:
#      - "19530:19530"
#    depends_on:
#      - "etcd"
#      - "minio"