version: '3.9'

services:
  api-gateway:
    container_name: api-gateway
    image: quay.io/jember.ai/api-gateway:${GATEWAY_IMAGE_TAG:-latest}
    restart: always
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}
      - AUTH_SERVER_URI=${AUTH_SERVER_URI}
      - AUTH_SERVER=${AUTH_SERVER}
      - AUTH_SERVER_PORT=${AUTH_SERVER_PORT}
      - DATA_INTAKE_SERVER=${INTAKE_SERVER}
      - DATA_INTAKE_SERVER_PORT=${INTAKE_SERVER_PORT}
      - DATA_INTAKE_OA3_SERVER=${OA3_SERVER}
      - DATA_INTAKE_OA3_SERVER_PORT=${OA3_SERVER_PORT}
      - CHAT_SERVER=${CHAT_SERVER}
      - CHAT_SERVER_PORT=${CHAT_SERVER_PORT}
      - SERVER_PORT=${GATEWAY_SERVER_PORT}
      - LOG_LEVEL=${GATEWAY_LOG_LEVEL}
    depends_on:
      - auth-server
      # - data-intake
      - oa3-docs
    ports:
      - ${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}

  auth-server:
    container_name: auth-server
    image: quay.io/jember.ai/spring-auth-server:${AUTH_IMAGE_TAG:-latest}
    restart: always
    environment:
      - JEMBER_SECRET=${JEMBER_SECRET}
      - JEMBER2_SECRET=${JEMBER2_SECRET}
      - GATEWAY_SERVER=${GATEWAY_SERVER}
      - GATEWAY_SERVER_PORT=${GATEWAY_SERVER_PORT}
      - SERVER_PORT=${AUTH_SERVER_PORT}
      - LOG_LEVEL=${AUTH_LOG_LEVEL}

  data-intake:
    container_name: data-intake
    image: quay.io/jember.ai/data-intake-rag-service:${INTAKE_IMAGE_TAG:-latest}
    restart: always
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=${INTAKE_SERVER_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_FLYWAY_URL=${SPRING_FLYWAY_URL}
      - SPRING_FLYWAY_USER=${SPRING_FLYWAY_USER}
      - SPRING_FLYWAY_PASSWORD=${SPRING_FLYWAY_PASSWORD}
      - ORG_JEMBERAI_DATASOURCE_PRIMARY_URL=${SPRING_DATASOURCE_URL}
      - ORG_JEMBERAI_DATASOURCE_PRIMARY_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - ORG_JEMBERAI_DATASOURCE_PRIMARY_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - ORG_JEMBERAI_DATASOURCE_PRIMARY_DRIVER-CLASS-NAME=org.postgresql.Driver
      - ORG_JEMBERAI_JPA_PRIMARY_HIBERNATE_DDL-AUTO=validate
      - ORG_JEMBERAI_DATASOURCE_KEYSTORE_URL=${SPRING_DATASOURCE_URL}
      - ORG_JEMBERAI_DATASOURCE_KEYSTORE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - ORG_JEMBERAI_DATASOURCE_KEYSTORE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - ORG_JEMBERAI_DATASOURCE_KEYSTORE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - ORG_JEMBERAI_JPA_KEYSTORE_HIBERNATE_DDL-AUTO=validate
      - ORG_JEMBERAI_DATASOURCE_KEYSTORE-FLYWAY_URL=${SPRING_FLYWAY_URL}
      - ORG_JEMBERAI_DATASOURCE_KEYSTORE-FLYWAY_USERNAME=${SPRING_FLYWAY_USER}
      - ORG_JEMBERAI_DATASOURCE_KEYSTORE-FLYWAY_PASSWORD=${SPRING_FLYWAY_PASSWORD}
      - ORG_JEMBERAI_DATASOURCE_KEYSTORE-FLYWAY_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_AI_VECTORSTORE_MILVUS_CLIENT_HOST=${SPRING_AI_VECTORSTORE_MILVUS_CLIENT_HOST}
      - SPRING_AI_VECTORSTORE_MILVUS_CLIENT_PORT=${SPRING_AI_VECTORSTORE_MILVUS_CLIENT_PORT}
      - SPRING_AI_VECTORSTORE_MILVUS_CLIENT_USERNAME=${SPRING_AI_VECTORSTORE_MILVUS_CLIENT_USERNAME}
      - SPRING_AI_VECTORSTORE_MILVUS_CLIENT_PASSWORD=${SPRING_AI_VECTORSTORE_MILVUS_CLIENT_PASSWORD}
      

  oa3-docs:
    container_name: oa3-docs
    image: quay.io/jember.ai/jember-oa3:${OA3_IMAGE_TAG:-latest}
    restart: always

  streamlit-chat:
    container_name: streamlit-chat
    image: quay.io/jember.ai/streamlit-chat:${CHAT_IMAGE_TAG:-latest}
    restart: always
    environment:
      - EMBEDDING_MODEL=text-embedding-3-small 
      - LLM_MODEL=gpt-4-turbo
      - OPENAI_API_KEY=sk-
      - DATA_INTAKE_URL=${GATEWAY_SERVER_URI}
      - DATA_INTAKE_CLIENT_ID=${JEMBER_CLIENT}
      - DATA_INTAKE_CLIENT_SECRET=${JEMBER_SECRET}
      - DATA_INTAKE_ACCESS_TOKEN=
      - CHAT_TITLE=JemberAI Chat
      - CHAT_LOGO=https://avatars.githubusercontent.com/u/175445266
      - CHAT_PROMPT_LABEL=Message JemberAI Chat
      - CHAT_FAVICON=":left_speech_bubble:"
      - CHAT_INITIAL_QUESTION=Welcome to JemberAI Chat how can I help you?

networks:
  default:
    name: jember